version: '3.8'

services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: house_price_prediction_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
